/**
 * ============================================================
 *  CHUNHUI_WEB — 网站内容配置文件
 *  数据来源：原网站 www.chunhuidoors.com (2026年5月爬取)
 * ============================================================
 */

const SITE_DATA = {

  // ── 公司基本信息 ──────────────────────────────────────────
  company: {
    name: "中山春晖门业有限公司",
    nameEn: "CHUNHUI DOOR",
    slogan: "春晖木门",
    sloganSub: "专注木门制造 · 意大利德国进口设备 · 畅销国内外",
    founded: "2004",
    phone: "0760-8820 3678",
    mobile: "13809689692",
    email: "7477461@qq.com",
    address: "广东省中山市五桂山镇龙塘工业大道7号",
    branchAddress: "广东省中山市南区恒美园山仔工业区",
    contactPerson: "司徒春涛",
    wechat: "chunhui_door",
    icp: "粤ICP备2025498719号-1",
  },

  // ── 首页核心数据 ──────────────────────────────────────────
  stats: [
    { number: "20年", label: "专注门业制造" },
    { number: "500+", label: "全国加盟门店" },
    { number: "274款", label: "在售产品型号" },
    { number: "畅销", label: "国内外市场" },
  ],

  // ── 产品分类导航（产品中心筛选）───────────────────────────────
  productCategories: [
    "全部", "生态门", "实木烤漆门", "铝木门", "玻璃门"
  ],

  // ── 产品中心数据 ───────────────────────────────────────────
  productCenter: {
    hero: {
      eyebrow: "PRODUCT CENTER",
      title: "让每一樘门，成为空间的秩序与温度",
      desc: "从生态门、实木烤漆门到铝木门，围绕材质、工艺、空间气质与长期使用稳定性，为不同家居风格提供成套木门选择。",
      image: "chanpinzhanshi/wuqimen/shengtaimen/国潮墨影系曲美101-烟熏柚木1_1.jpg",
      highlights: [
        { value: "274款", label: "产品型号" },
        { value: "3大", label: "核心品类" },
        { value: "500+", label: "门店支持" },
      ],
    },
    navGroups: [
      {
        title: "产品品类",
        items: [
          { label: "生态门", desc: "多色饰面，轻奢百搭", cat: "生态门" },
          { label: "实木烤漆门", desc: "雕刻线条，质感稳定", cat: "实木烤漆门" },
          { label: "铝木门", desc: "防潮抗变，同色一体", cat: "铝木门" },
          { label: "玻璃门", desc: "通透采光，厨卫友好", cat: "玻璃门" },
        ],
      },
      {
        title: "风格系列",
        items: [
          { label: "国潮墨影", desc: "东方木纹与现代线条", cat: "生态门" },
          { label: "经典平雕", desc: "耐看线型，适配广", cat: "实木烤漆门" },
          { label: "橡木深雕", desc: "立体雕刻，高端感强", cat: "实木烤漆门" },
          { label: "健康无漆", desc: "低味环保，安心入住", cat: "铝木门" },
        ],
      },
    ],
    categories: [
      {
        title: "生态门",
        subtitle: "国潮墨影系列",
        desc: "免漆饰面与细腻木纹，适合现代、轻奢、简约家居。",
        count: "80+",
        image: "chanpinzhanshi/wuqimen/shengtaimen/国潮墨影系S036辛格榆木_1.jpg",
      },
      {
        title: "实木烤漆门",
        subtitle: "平雕 / 深雕 / 木皮工艺",
        desc: "保留传统木门质感，线条层次更丰富，适合改善型装修。",
        count: "180+",
        image: "chanpinzhanshi/kaoqimen/shimukaoqimen/橡木深雕门系列CHA-97_1.jpg",
      },
      {
        title: "铝木门",
        subtitle: "M9健康无漆木门",
        desc: "同色一体、防潮抗变，更适合南方潮湿环境与长期使用。",
        count: "2款",
        image: "chanpinzhanshi/wuqimen/lvmumen/M9系列 同色铝木门·健康无漆木门（防潮抗变 - M9绿色健康板）_1.png",
      },
      {
        title: "玻璃门",
        subtitle: "厨卫与采光空间",
        desc: "窄边线条与玻璃材质，让小空间保持明亮通透。",
        count: "15款",
        image: "chanpinzhanshi/kaoqimen/shimukaoqimen/玻璃门系列CHA-B01_1.jpg",
      },
    ],
    filters: [
      { title: "按品类", values: ["生态门", "实木烤漆门", "铝木门", "玻璃门"] },
      { title: "按系列", values: ["国潮墨影", "平雕门", "橡木深雕", "木皮工艺"] },
      { title: "按需求", values: ["健康环保", "防潮抗变", "经典百搭", "通透采光"] },
    ],
    recommendations: [
      {
        title: "热门推荐",
        name: "国潮墨影系·曲美101",
        image: "chanpinzhanshi/wuqimen/shengtaimen/国潮墨影系曲美101-烟熏柚木1_1.jpg",
      },
      {
        title: "新品主推",
        name: "M9同色铝木门",
        image: "chanpinzhanshi/wuqimen/lvmumen/M9系列 同色铝木门·健康无漆木门（防潮抗变 - M9绿色健康板）_1.png",
      },
    ],
    catalogTitle: "全部产品",
    catalogDesc: "精选热销与主推型号，覆盖现代简约、国潮木纹、经典雕刻与通透采光空间。",
  },

  // ── 产品中心精选产品 ───────────────────────────────────────
  products: [
    {
      id: 1,
      name: "国潮墨影系·曲美101烟熏柚木",
      series: "生态门",
      desc: "烟熏柚木纹理搭配克制线条，适合现代轻奢与东方美学空间。",
      tag: "国潮系列",
      price: "询价定制",
      image: "chanpinzhanshi/wuqimen/shengtaimen/国潮墨影系曲美101-烟熏柚木1_1.jpg",
      accent: "#8B3A2A",
    },
    {
      id: 2,
      name: "M9系列 同色铝木门",
      series: "铝木门",
      desc: "健康无漆木门，防潮抗变，M9绿色健康板，同色一体化设计。",
      tag: "健康环保",
      price: "询价定制",
      image: "chanpinzhanshi/wuqimen/lvmumen/M9系列 同色铝木门·健康无漆木门（防潮抗变 - M9绿色健康板）_1.png",
      accent: "#2A5C3A",
    },
    {
      id: 3,
      name: "橡木深雕门系列·CHA-97",
      series: "实木烤漆门",
      desc: "橡木质感与深雕工艺结合，立体感强，适合高端家居空间。",
      tag: "匠心智造",
      price: "询价定制",
      image: "chanpinzhanshi/kaoqimen/shimukaoqimen/橡木深雕门系列CHA-97_1.jpg",
      accent: "#5C4A2A",
    },
    {
      id: 4,
      name: "国潮墨影系·S036辛格榆木",
      series: "生态门",
      desc: "辛格榆木纹理清晰自然，适合年轻家庭的简约装修风格。",
      tag: "人气推荐",
      price: "询价定制",
      image: "chanpinzhanshi/wuqimen/shengtaimen/国潮墨影系S036辛格榆木_1.jpg",
      accent: "#2A3A5C",
    },
    {
      id: 5,
      name: "平雕门系列·CHA-24",
      series: "实木烤漆门",
      desc: "经典平雕设计，线条简洁流畅，百搭多种家装风格。",
      tag: "经典款",
      price: "询价定制",
      image: "chanpinzhanshi/kaoqimen/shimukaoqimen/平雕门系列CHA-24_1.jpg",
      accent: "#7A3A1A",
    },
    {
      id: 6,
      name: "国潮墨影系·FC-010烟熏柚木",
      series: "生态门",
      desc: "国潮墨影入门款，烟熏柚木饰面，高性价比之选。",
      tag: "热销爆款",
      price: "询价定制",
      image: "chanpinzhanshi/wuqimen/shengtaimen/国潮墨影系FC-010烟熏柚木1_1.jpg",
      accent: "#3A2A5C",
    },
    {
      id: 7,
      name: "玻璃门系列·CHA-B01",
      series: "玻璃门",
      desc: "适合厨卫、书房与采光过渡区，让空间保持轻盈通透。",
      tag: "通透采光",
      price: "询价定制",
      image: "chanpinzhanshi/kaoqimen/shimukaoqimen/玻璃门系列CHA-B01_1.jpg",
      accent: "#44636A",
    },
    {
      id: 8,
      name: "木皮工艺门系列·CHA-122",
      series: "实木烤漆门",
      desc: "木皮工艺保留自然纹理，兼顾稳定性与高级质感。",
      tag: "木皮工艺",
      price: "询价定制",
      image: "chanpinzhanshi/kaoqimen/shimukaoqimen/木皮工艺门系列CHA-122_1.jpg",
      accent: "#6A513C",
    },
    {
      id: 9,
      name: "国潮墨影系·D058冰山白",
      series: "生态门",
      desc: "干净的冰山白饰面，适合奶油风、现代风与小户型空间。",
      tag: "明亮百搭",
      price: "询价定制",
      image: "chanpinzhanshi/wuqimen/shengtaimen/国潮墨影系D058(黑)冰山白_1.jpg",
      accent: "#7E8588",
    },
  ],

  // ── 全部产品数据（按分类组织）─────────────────────────────
  allProducts: {
    "生态门": {
      folder: "chanpinzhanshi/wuqimen/shengtaimen",
      items: [
        { name: "国潮墨影系S038冰山白" },
        { name: "国潮墨影系D058(黑)冰山白" },
        { name: "国潮墨影系V06里德胡桃" },
        { name: "国潮墨影系FC-010冰山白" },
        { name: "国潮墨影系S036辛格榆木" },
        { name: "国潮墨影系D061(金)烟熏柚木2" },
        { name: "国潮墨影系曲美101烟熏柚木3" },
        { name: "国潮墨影系D062(金)烟熏柚木3" },
        { name: "国潮墨影系D001(黑)烟熏柚木2" },
        { name: "国潮墨影系FC-010塞纳灰" },
        { name: "国潮墨影系S029冰山白" },
        { name: "国潮墨影系SK002冰山白" },
        { name: "国潮墨影系D063(黑)烟熏柚木1" },
        { name: "国潮墨影系曲美202枫香梨木" },
        { name: "国潮墨影系曲美201烟熏柚木3" },
        { name: "国潮墨影系FC-021冰山白" },
        { name: "国潮墨影系D067(金)里德胡桃" },
        { name: "国潮墨影系D036(黑)塞纳灰" },
        { name: "国潮墨影系FC-010烟熏柚木1" },
        { name: "国潮墨影系8053冰山白" },
        { name: "国潮墨影系D067(黑)里德胡桃" },
        { name: "国潮墨影系FC-016烟熏柚木1" },
        { name: "国潮墨影系S035烟熏柚木1" },
        { name: "国潮墨影系SK001烟熏柚木1" },
        { name: "国潮墨影系D058(金)冰山白" },
        { name: "国潮墨影系FC-016烟熏柚木2" },
        { name: "国潮墨影系SK002烟熏柚木1" },
        { name: "国潮墨影系S033烟熏柚木3" },
        { name: "国潮墨影系SK001里德胡桃" },
        { name: "国潮墨影系S035塞纳灰" },
        { name: "国潮墨影系FC-010烟熏柚木2" },
        { name: "国潮墨影系D063(黑)烟熏柚木3" },
        { name: "国潮墨影系FC-016冰山白" },
        { name: "国潮墨影系D061(金)塞纳灰" },
        { name: "国潮墨影系S036烟熏柚木1" },
        { name: "国潮墨影系SK001冰山白" },
        { name: "国潮墨影系D061(金)烟熏柚木1" },
        { name: "国潮墨影系D001(黑)烟熏柚木1" },
        { name: "国潮墨影系S037塞纳灰" },
        { name: "国潮墨影系S035烟熏柚木2" },
        { name: "国潮墨影系S036烟熏柚木2" },
        { name: "国潮墨影系8053塞纳灰" },
        { name: "国潮墨影系D058(金)烟熏柚木1" },
        { name: "国潮墨影系D067(金)冰山白" },
        { name: "国潮墨影系S037烟熏柚木2" },
        { name: "国潮墨影系D001(黑)烟熏柚木3" },
        { name: "国潮墨影系D001(黑)塞纳灰" },
        { name: "国潮墨影系S037冰山白" },
        { name: "国潮墨影系SK001塞纳灰" },
        { name: "国潮墨影系V06冰山白" },
        { name: "国潮墨影系D062(金)塞纳灰" },
        { name: "国潮墨影系D063(黑)里德胡桃" },
        { name: "国潮墨影系曲美101烟熏柚木2" },
        { name: "国潮墨影系SK001烟熏柚木2" },
        { name: "国潮墨影系8053里德胡桃" },
        { name: "国潮墨影系D058(金)塞纳灰" },
        { name: "国潮墨影系8053烟熏柚木1" },
        { name: "国潮墨影系S035冰山白" },
        { name: "国潮墨影系D058(金)烟熏柚木2" },
        { name: "国潮墨影系D062(金)冰山白" },
        { name: "国潮墨影系曲美201烟熏柚木1" },
        { name: "国潮墨影系FC-021烟熏柚木1" },
        { name: "国潮墨影系D061(黑)塞纳灰" },
        { name: "国潮墨影系D061(金)冰山白" },
        { name: "国潮墨影系FC-021塞纳灰" },
        { name: "国潮墨影系S037烟熏柚木1" },
        { name: "国潮墨影系D061(黑)冰山白" },
        { name: "国潮墨影系D061(黑)烟熏柚木1" },
        { name: "国潮墨影系FC-021烟熏柚木2" },
        { name: "国潮墨影系D061(黑)烟熏柚木3" },
        { name: "国潮墨影系D063(黑)冰山白" },
        { name: "国潮墨影系V06塞纳灰" },
        { name: "国潮墨影系D067(黑)烟熏柚木1" },
        { name: "国潮墨影系S035烟熏柚木3" },
        { name: "国潮墨影系曲美101烟熏柚木1" },
        { name: "国潮墨影系8053烟熏柚木3" },
        { name: "国潮墨影系D058(黑)塞纳灰" },
        { name: "国潮墨影系曲美202枫香梨木" },
        { name: "国潮墨影系S038塞纳灰" },
        { name: "国潮墨影系D058(金)烟熏柚木3" },
        { name: "国潮墨影系D067(黑)塞纳灰" },
        { name: "国潮墨影系S038里德胡桃" },
        { name: "国潮墨影系D062(金)里德胡桃" },
        { name: "ENF+ 耐水净醛板木门" },
        { name: "国潮墨影系D067(黑)冰山白" },
      ],
    },
    "实木烤漆门": {
      folder: "chanpinzhanshi/kaoqimen/shimukaoqimen",
      items: [
        { name: "橡木深雕门系列CHA-97" },
        { name: "橡木深雕门系列CHA-79" },
        { name: "橡木深雕门系列CHA-77" },
        { name: "平雕门系列CHA-24" },
        { name: "平雕门系列CHA-59" },
        { name: "木皮工艺门系列CHA-146" },
        { name: "平雕门系列CHA-04" },
        { name: "时尚白门系列CHA-176" },
        { name: "平雕门系列CHA-62" },
        { name: "平雕门系列CHA-73" },
        { name: "橡木深雕门系列CHA-95" },
        { name: "橡木深雕门系列CHA-98" },
        { name: "橡木深雕门系列CHA-99" },
        { name: "橡木深雕门系列CHA-96" },
        { name: "平雕门系列CHA-27" },
        { name: "平雕门系列CHA-43" },
        { name: "平雕门系列CHA-35" },
        { name: "平雕门系列CHA-16" },
        { name: "平雕门系列CHA-33" },
        { name: "平雕门系列CHA-75" },
        { name: "平雕门系列CHA-69" },
        { name: "平雕门系列CHA-58" },
        { name: "时尚白门系列CHA-175" },
        { name: "平雕门系列CHA-76" },
        { name: "平雕门系列CHA-28" },
        { name: "平雕门系列CHA-30" },
        { name: "平雕门系列CHA-71" },
        { name: "平雕门系列CHA-48" },
        { name: "平雕门系列CHA-72" },
        { name: "平雕门系列CHA-38" },
        { name: "平雕门系列CHA-57" },
        { name: "平雕门系列CHA-61" },
        { name: "平雕门系列CHA-67" },
        { name: "平雕门系列CHA-74" },
        { name: "平雕门系列CHA-15" },
        { name: "平雕门系列CHA-19" },
        { name: "平雕门系列CHA-44" },
        { name: "平雕门系列CHA-29" },
        { name: "平雕门系列CHA-47" },
        { name: "平雕门系列CHA-81" },
        { name: "平雕门系列CHA-82" },
        { name: "平雕门系列CHA-83" },
        { name: "平雕门系列CHA-31" },
        { name: "平雕门系列CHA-08" },
        { name: "平雕门系列CHA-39" },
        { name: "平雕门系列CHA-42" },
        { name: "平雕门系列CHA-46" },
        { name: "平雕门系列CHA-49" },
        { name: "时尚白门系列CHA-178" },
        { name: "平雕门系列CHA-13" },
        { name: "时尚白门系列CHA-170" },
        { name: "平雕门系列CHA-68" },
        { name: "木皮工艺门系列CHA-138" },
        { name: "木皮工艺门系列CHA-139" },
        { name: "平雕门系列CHA-52" },
        { name: "平雕门系列CHA-53" },
        { name: "平雕门系列CHA-55" },
        { name: "平雕门系列CHA-56" },
        { name: "平雕门系列CHA-80" },
        { name: "平雕门系列CHA-84" },
        { name: "平雕门系列CHA-85" },
        { name: "木皮工艺门系列CHA-133" },
        { name: "木皮工艺门系列CHA-134" },
        { name: "木皮工艺门系列CHA-135" },
        { name: "木皮工艺门系列CHA-136" },
        { name: "木皮工艺门系列CHA-142" },
        { name: "木皮工艺门系列CHA-143" },
        { name: "木皮工艺门系列CHA-144" },
        { name: "木皮工艺门系列CHA-145" },
        { name: "木皮工艺门系列CHA-147" },
        { name: "木皮工艺门系列CHA-148" },
        { name: "木皮工艺门系列CHA-149" },
        { name: "木皮工艺门系列CHA-150" },
        { name: "木皮工艺门系列CHA-151" },
        { name: "木皮工艺门系列CHA-152" },
        { name: "木皮工艺门系列CHA-153" },
        { name: "木皮工艺门系列CHA-154" },
        { name: "木皮工艺门系列CHA-155" },
        { name: "木皮工艺门系列CHA-156" },
        { name: "木皮工艺门系列CHA-157" },
        { name: "木皮工艺门系列CHA-158" },
        { name: "木皮工艺门系列CHA-159" },
        { name: "木皮工艺门系列CHA-160" },
        { name: "木皮工艺门系列CHA-161" },
        { name: "木皮工艺门系列CHA-162" },
        { name: "木皮工艺门系列CHA-163" },
        { name: "木皮工艺门系列CHA-164" },
        { name: "木皮工艺门系列CHA-165" },
        { name: "木皮工艺门系列CHA-166" },
        { name: "木皮工艺门系列CHA-167" },
        { name: "木皮工艺门系列CHA-168" },
        { name: "平雕门系列CHA-06" },
        { name: "平雕门系列CHA-11" },
        { name: "平雕门系列CHA-12" },
        { name: "平雕门系列CHA-14" },
        { name: "平雕门系列CHA-17" },
        { name: "平雕门系列CHA-18" },
        { name: "平雕门系列CHA-20" },
        { name: "平雕门系列CHA-21" },
        { name: "平雕门系列CHA-22" },
        { name: "平雕门系列CHA-23" },
        { name: "平雕门系列CHA-25" },
        { name: "平雕门系列CHA-26" },
        { name: "平雕门系列CHA-32" },
        { name: "平雕门系列CHA-34" },
        { name: "平雕门系列CHA-36" },
        { name: "平雕门系列CHA-37" },
        { name: "平雕门系列CHA-40" },
        { name: "平雕门系列CHA-41" },
        { name: "平雕门系列CHA-45" },
        { name: "平雕门系列CHA-50" },
        { name: "平雕门系列CHA-51" },
        { name: "平雕门系列CHA-54" },
        { name: "平雕门系列CHA-60" },
        { name: "平雕门系列CHA-63" },
        { name: "平雕门系列CHA-64" },
        { name: "平雕门系列CHA-65" },
        { name: "平雕门系列CHA-66" },
        { name: "平雕门系列CHA-70" },
        { name: "平雕门系列CHA-78" },
        { name: "时尚白门系列CHA-171" },
        { name: "时尚白门系列CHA-172" },
        { name: "时尚白门系列CHA-173" },
        { name: "时尚白门系列CHA-174" },
        { name: "时尚白门系列CHA-177" },
        { name: "时尚白门系列CHA-179" },
        { name: "时尚白门系列CHA-180" },
        { name: "木皮工艺门系列CHA-137" },
        { name: "木皮工艺门系列CHA-140" },
        { name: "木皮工艺门系列CHA-141" },
        { name: "轻奢极简系列CHA-181" },
        { name: "轻奢极简系列CHA-182" },
        { name: "轻奢极简系列CHA-183" },
        { name: "轻奢极简系列CHA-184" },
        { name: "轻奢极简系列CHA-185" },
        { name: "轻奢极简系列CHA-186" },
        { name: "轻奢极简系列CHA-187" },
        { name: "轻奢极简系列CHA-188" },
        { name: "轻奢极简系列CHA-189" },
        { name: "轻奢极简系列CHA-190" },
        { name: "轻奢极简系列CHA-191" },
        { name: "轻奢极简系列CHA-192" },
        { name: "轻奢极简系列CHA-193" },
        { name: "轻奢极简系列CHA-194" },
        { name: "轻奢极简系列CHA-195" },
        { name: "轻奢极简系列CHA-196" },
        { name: "轻奢极简系列CHA-197" },
        { name: "轻奢极简系列CHA-198" },
        { name: "轻奢极简系列CHA-199" },
        { name: "平雕门系列CHA-01" },
        { name: "平雕门系列CHA-02" },
        { name: "平雕门系列CHA-03" },
        { name: "平雕门系列CHA-05" },
        { name: "平雕门系列CHA-07" },
        { name: "平雕门系列CHA-09" },
        { name: "平雕门系列CHA-10" },
        { name: "木皮工艺门系列CHA-127" },
        { name: "木皮工艺门系列CHA-128" },
        { name: "木皮工艺门系列CHA-129" },
        { name: "木皮工艺门系列CHA-130" },
        { name: "木皮工艺门系列CHA-131" },
        { name: "木皮工艺门系列CHA-132" },
        { name: "时尚白门系列CHA-169" },
        { name: "轻奢极简系列CHA-200" },
      ],
    },
    "铝木门": {
      folder: "chanpinzhanshi/wuqimen/lvmumen",
      items: [
        { name: "M9系列 同色铝木门·健康无漆木门" },
        { name: "瑞丽同色系列 磁吸静音铝木门" },
      ],
    },
  },

  // ── 关于我们（guanyuwomen/）──────────────────────────────
  about: {
    title: "专注木门制造，品质铸就品牌",
    content: "中山春晖门业有限公司坐落在广东中山市，产品质量过硬，设计美观实用，价格合理。平雕系列产品款式新颖，多年来畅销国内外市场，赢得了广大用户和经销商的良好口碑。春晖木业拥有从意大利、德国进口的先进生产设备进行流水作业，创立了「春晖」木门品牌。传承「春晖」，将精湛工艺及中国传统文化融入每一细节，浑然天成，融汇匠心，引导行业潮流。我们坚持以满足国内中端市场为原则，聘请德国、意大利著名设计师加盟，将所有先进工艺制造技术与国际化原则设计相结合。在未来的营销理念中，我们将进一步完善严格的品质管理体系，提高产品质量标准，以优良的品质、优质的服务、低廉的价格奉献社会，回报客商！您的满意就是我们永恒的追求！",
    image: "guanyuwomen/about_main.jpg",
    highlights: [
      { icon: "🏭", title: "进口设备", desc: "意大利、德国进口先进生产设备，流水作业" },
      { icon: "🎨", title: "国际设计", desc: "德意著名设计师加盟，引领行业潮流" },
      { icon: "🛡️", title: "品质保证", desc: "严格品质管理体系，产品质量过硬" },
      { icon: "🌍", title: "畅销国内外", desc: "平雕系列畅销国内外，赢得良好口碑" },
    ],
    timeline: [
      { year: "2004", event: "春晖门业成立，首条生产线投产" },
      { year: "2009", event: "荣获行业认可，经销商网络逐步覆盖全国" },
      { year: "2014", event: "引进意大利、德国进口先进生产设备" },
      { year: "2018", event: "推出国潮墨影系列，市场反响热烈" },
      { year: "2024", event: "全国加盟门店突破500家，产品远销海外" },
    ],
  },

  // ── 新闻动态（xinwendongtai/）─────────────────────────────
  news: [
    {
      id: 1,
      date: "2025-05-18",
      category: "保养知识",
      title: "春晖木门丨这些木门保养的细节，你知道吗？",
      summary: "春晖木门教你几招家里木门的保养方法：木门清洁四忌、木门清洁五推荐、木门日常使用维护。为了保持木门表面的光泽度和延长使用寿命，应该定期对木门进行维护保养。",
      image: "xinwendongtai/news_01.jpg",
    },
    {
      id: 2,
      date: "2025-04-22",
      category: "品牌动态",
      title: "春晖木门丨论选对好木门对家居空间的重要性",
      summary: "木门是每个家庭的必备品，木门属于耐用品，最考验选材的优质性，耐用性。春晖木门采用进口木材，通过国标层层检查，反复测试，为您打造高品质家居空间。",
      image: "xinwendongtai/news_02.jpg",
    },
    {
      id: 3,
      date: "2025-03-15",
      category: "品牌动态",
      title: "春晖木门 | 化繁为简，细品美好生活",
      summary: "越少越显高级感。简约而不简单，一个具有格调品质及艺术气息的理想之家。在这个光与生活融合为一的灵韵空间里，优越不言自彰。春晖木门，为美好生活而生。",
      image: "xinwendongtai/news_03.jpg",
    },
  ],

  // ── 招商加盟板块 ─────────────────────────────────────────
  advantages: [
    { icon: "💰", title: "行业风口", desc: "行业最后的风口，再造100名家居行业千万大商" },
    { icon: "🏪", title: "全国500+门店", desc: "全国500+加盟店邀您共享财富，紧跟一线品牌" },
    { icon: "📞", title: "全程扶持", desc: "从选址到开业全程指导，专业团队一对一扶持" },
    { icon: "🚚", title: "优质供应链", desc: "意大利、德国进口设备生产，品质保障货源稳定" },
  ],

  // ── 联系信息 ─────────────────────────────────────────────
  contact: {
    salesPhone: "0760-8820 3678",
    mobilePhone: "13809689692",
    afterSalePhone: "0760-8820 3678",
    workHours: "周一至周日 8:00 - 18:00",
    contactPerson: "司徒春涛",
    wechatQR: "lianxiwomen/wechat_qr.jpg",
    cta: "立即咨询 · 免费获取报价",
    ctaSub: "今日咨询，优先排期 · 全国500+门店为您服务",
  },

  // ── 导航菜单 ─────────────────────────────────────────────
  nav: [
    { label: "首页", href: "index.html", key: "home" },
    { label: "产品中心", href: "products.html", key: "products" },
    { label: "关于春晖", href: "about.html", key: "about" },
    { label: "新闻动态", href: "news.html", key: "news" },
    { label: "招商加盟", href: "join.html", key: "join" },
  ],
};

window.SITE_DATA = SITE_DATA;
